name: megrim
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  colorful_iconify_flutter: ^0.0.2
  iconify_flutter: ^0.0.4
  glassmorphism_ui: ^0.3.0
  google_nav_bar: ^5.0.6
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  uuid: ^4.4.2
  font_awesome_flutter: ^10.1.0
  animated_text_kit: ^4.2.3
  http: ^1.2.1
  web_socket_channel: ^3.0.3
  mailer: ^6.4.1
  flutter_spinkit: ^5.0.0 
  get: ^4.6.5
  flutter_smart_dialog: ^4.9.7+9
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  liquid_pull_to_refresh: ^3.0.1
  another_flushbar: ^1.12.30
  ntp: ^2.0.0
  flutter_blue_plus: ^1.34.5
  floating_bottom_navigation_bar: ^1.5.2
  permission_handler: ^12.0.0+1
  bluetooth_low_energy: ^6.0.2
  shimmer: ^3.0.0
  pretty_animated_text: ^2.0.0
  animated_flip_counter: ^0.3.4
  device_info_plus: ^11.3.0
  package_info_plus: ^8.3.0
  latlong2: ^0.9.1
  flutter_stripe: ^11.5.0
  firebase_core: ^3.14.0
  firebase_crashlytics: ^4.3.7
  firebase_messaging: ^15.2.7
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  flutter_map: ^7.0.2
  image_picker: ^0.8.7+3
  path: ^1.8.3
  intl: ^0.20.2
  flutter_animate: ^4.5.2
  

  
 
  
  
  
 
  
  
 



  
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/Images/Icon.png"

flutter:
  uses-material-design: true

  assets:
    - lib/Images/Icon.png